### ISSUE TITLE
引入对应 jar 包 但无法启动

### ISSUE THREAD

**Issue by HANXU2018** [go-cqhttp/java#19]
引入对应 jar 包 但无法启动
```
        <dependency>
            <groupId>com.zhuangxv</groupId>
            <artifactId>bot-core</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>/Users/Desktop/bot-core-1.0.0.jar</systemPath>
        </dependency>
```
Eeupt 框架引入 bot-core jar包  在启动类 添加 @EnableBot 注解
```
package com.example.demo;

import com.example.demo.proxy.TestLoginProxy;
import com.zhuangxv.bot.EnableBot;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import xyz.erupt.core.annotation.EruptScan;
import xyz.erupt.upms.fun.EruptLogin;

import java.awt.*;
import java.net.URI;

@EnableBot
@SpringBootApplication
@EruptLogin(TestLoginProxy.class)
@EntityScan
@EruptScan
public class ExampleApplication extends SpringBootServletInitializer {

    //详细使用方法详见项目内 README.md 文件说明
    public static void main(String[] args) {
        SpringApplication.run(ExampleApplication.class, args);
        try {
            System.setProperty("java.awt.headless", "false");
            Desktop.getDesktop().browse(new URI("http://localhost:7788"));
        } catch (Exception e) {
            System.setProperty("java.awt.headless", "true");
        }
        System.err.println("详细使用方法，请阅读：README.md");
    }

    //打WAR包的配置
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(ExampleApplication.class);
    }

}

```

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-26 00:47:39.899 ERROR 17631 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.zhuangxv.bot.core.BotDispatcher': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.zhuangxv.bot.core.BotDispatcher] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:289) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1284) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1201) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar:2.4.5]
	at com.example.demo.ExampleApplication.main(ExampleApplication.java:25) [classes/:na]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.zhuangxv.bot.core.BotDispatcher] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.3.6.jar:5.3.6]
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321) ~[spring-core-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:267) ~[spring-beans-5.3.6.jar:5.3.6]
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSONObject
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_282]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_282]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_282]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.3.6.jar:5.3.6]
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSONObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[na:1.8.0_282]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[na:1.8.0_282]
	... 25 common frames omitted


Process finished with exit code 1
```

**Comment by HANXU2018** [comment]
观察日志发现 fastjson 未被 maven 自动引入 单独引入到 pom.xml 文件后重新编译可启动

```
 <dependency>
            <groupId>com.zhuangxv</groupId>
            <artifactId>bot-core</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>/Users/hanxu/Desktop/bot-core-1.0.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.78</version>
        </dependency>

```

**Comment by HANXU2018** [comment]
netty 依赖缺失
 
```
<dependency>
            <groupId>com.zhuangxv</groupId>
            <artifactId>bot-core</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>/Users/hanxu/Desktop/bot-core-1.0.0.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.78</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>

```

**Comment by xiaoxu97** [comment]
你引用方法错了，将项目mvn install后直接引用即可，无依赖丢失
